[features]
seeds = false
skip-lint = false
[programs.localnet]
stake_program = "D7MtJpDRCFLVrqRZU5qY7PjhTaL97QFuamWn8PSWHv6o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sai.vaddi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
